# Generated by Django 5.2 on 2025-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_remove_message_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='admin_display_name',
            field=models.CharField(blank=True, help_text='Custom name for the admin/support agent in this session', max_length=100, null=True),
        ),
    ]
