# Generated by Django 5.2 on 2025-05-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_admin_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='notified',
            field=models.BooleanField(default=False, help_text='Whether the admin has been notified of this session'),
        ),
    ]
