# Generated by Django 5.2 on 2025-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
