# Generated by Django 5.2 on 2025-05-01 11:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shipment_destination_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
