# Generated by Django 5.2 on 2025-05-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shipment_destination_name_shipment_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('browser', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=20)),
                ('user_agent', models.TextField()),
            ],
        ),
    ]
